# Generated by Django 4.2.7 on 2023-11-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resource", "0002_init_database"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="career",
            options={"verbose_name_plural": "Careers"},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name_plural": "Collections"},
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={"verbose_name_plural": "Entities"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Faculties"},
        ),
        migrations.AlterModelOptions(
            name="format",
            options={"verbose_name_plural": "Formats"},
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={"verbose_name_plural": "Keywords"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="license",
            options={"verbose_name_plural": "Licenses"},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"verbose_name_plural": "Resources"},
        ),
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={"verbose_name_plural": "Resource Categories"},
        ),
        migrations.AlterModelOptions(
            name="resourceorigin",
            options={"verbose_name_plural": "Resource Origins"},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name_plural": "Schools"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name_plural": "Subjetcs"},
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={"verbose_name_plural": "Themes"},
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Death"),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="career",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="format",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="abstract",
            field=models.TextField(verbose_name="Abstract"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="adquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Adquisition Date"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="author",
            field=models.ManyToManyField(to="resource.author", verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="career",
            field=models.ManyToManyField(to="resource.career", verbose_name="Career"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="coverage_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Coverage (End)"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="coverage_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Coverage (Start)"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="edition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Edition"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.entity",
                verbose_name="Entity",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="format",
            field=models.ManyToManyField(to="resource.format", verbose_name="Format"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="international_id",
            field=models.CharField(max_length=255, verbose_name="International ID"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="keyword",
            field=models.ManyToManyField(to="resource.keyword", verbose_name="Keyword"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="language",
            field=models.ManyToManyField(
                to="resource.language", verbose_name="Language"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.license",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="publish_date",
            field=models.DateField(verbose_name="Publish Date"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.resourcecategory",
                verbose_name="Resource Category",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.resourceorigin",
                verbose_name="Resource Origin",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="theme",
            field=models.ManyToManyField(to="resource.theme", verbose_name="Theme"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="resourceorigin",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
